/**
 * PR Comment Tests
 * Per Test Cases v1.9.3 - PR/CI Integration Tests
 */
import { describe, test, expect } from 'vitest';

// Types for PR comment generation
interface InferencePoint {
  id: string;
  file: string;
  line: number;
  provider: string;
  model: string;
}

interface Issue {
  id: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  category: string;
  title: string;
  description: string;
  file: string;
  line: number;
}

interface AnalysisResult {
  inferencePoints: InferencePoint[];
  issues: Issue[];
  summary: {
    totalInferencePoints: number;
    criticalIssues: number;
    highIssues: number;
    mediumIssues: number;
    lowIssues: number;
  };
}

// PR Comment generator (to be implemented in src/pr-comment.ts)
function generatePRComment(result: AnalysisResult): string {
  const lines: string[] = [];

  // Header
  lines.push('## PeakInfer Analysis');
  lines.push('');

  // Summary
  lines.push(`Found **${result.summary.totalInferencePoints}** inference points`);
  lines.push('');

  // Issues by severity
  if (result.summary.criticalIssues > 0 || result.summary.highIssues > 0) {
    lines.push('### Issues Found');
    lines.push('');

    const critical = result.issues.filter(i => i.severity === 'critical');
    const high = result.issues.filter(i => i.severity === 'high');

    for (const issue of [...critical, ...high].slice(0, 5)) {
      const emoji = issue.severity === 'critical' ? ':red_circle:' : ':orange_circle:';
      lines.push(`${emoji} **${issue.severity.toUpperCase()}**: ${issue.title}`);
      lines.push(`   - ${issue.file}:${issue.line}`);
      lines.push(`   - ${issue.description}`);
      lines.push('');
    }
  }

  // No issues case
  if (result.issues.length === 0) {
    lines.push(':white_check_mark: No issues found');
  }

  // Footer
  lines.push('---');
  lines.push('*Generated by [PeakInfer](https://peakinfer.dev)*');

  return lines.join('\n');
}

function generateCompactComment(result: AnalysisResult): string {
  const criticalHigh = result.summary.criticalIssues + result.summary.highIssues;

  if (criticalHigh === 0) {
    return `:white_check_mark: PeakInfer: ${result.summary.totalInferencePoints} inference points, no critical issues`;
  }

  return `:warning: PeakInfer: ${result.summary.totalInferencePoints} inference points, ${criticalHigh} critical/high issues`;
}

function shouldBlockPR(result: AnalysisResult, threshold: 'critical' | 'high' | 'medium'): boolean {
  if (threshold === 'critical') {
    return result.summary.criticalIssues > 0;
  }
  if (threshold === 'high') {
    return result.summary.criticalIssues > 0 || result.summary.highIssues > 0;
  }
  return result.summary.criticalIssues > 0 || result.summary.highIssues > 0 || result.summary.mediumIssues > 0;
}

describe('PR Comment Generation', () => {
  test('Generates markdown comment with issues', () => {
    const result: AnalysisResult = {
      inferencePoints: [
        { id: 'ip-1', file: 'src/chat.ts', line: 42, provider: 'anthropic', model: 'claude-sonnet-4-20250514' },
      ],
      issues: [
        {
          id: 'issue-1',
          severity: 'critical',
          category: 'cost',
          title: 'Expensive model for simple task',
          description: 'Using claude-opus for chat completion',
          file: 'src/chat.ts',
          line: 42,
        },
      ],
      summary: {
        totalInferencePoints: 1,
        criticalIssues: 1,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    const comment = generatePRComment(result);

    expect(comment).toContain('## PeakInfer Analysis');
    expect(comment).toContain('1 inference points');
    expect(comment).toContain('CRITICAL');
    expect(comment).toContain('Expensive model');
    expect(comment).toContain('src/chat.ts:42');
  });

  test('Generates clean comment when no issues', () => {
    const result: AnalysisResult = {
      inferencePoints: [
        { id: 'ip-1', file: 'src/chat.ts', line: 42, provider: 'anthropic', model: 'claude-sonnet-4-20250514' },
      ],
      issues: [],
      summary: {
        totalInferencePoints: 1,
        criticalIssues: 0,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    const comment = generatePRComment(result);

    expect(comment).toContain('No issues found');
    expect(comment).not.toContain('CRITICAL');
  });

  test('Limits issues to top 5', () => {
    const issues: Issue[] = Array.from({ length: 10 }, (_, i) => ({
      id: `issue-${i}`,
      severity: 'high' as const,
      category: 'cost',
      title: `Issue ${i}`,
      description: 'Test issue',
      file: 'src/chat.ts',
      line: i + 1,
    }));

    const result: AnalysisResult = {
      inferencePoints: [],
      issues,
      summary: {
        totalInferencePoints: 0,
        criticalIssues: 0,
        highIssues: 10,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    const comment = generatePRComment(result);

    // Should only show 5 issues max
    const highCount = (comment.match(/HIGH/g) || []).length;
    expect(highCount).toBeLessThanOrEqual(5);
  });

  test('Includes PeakInfer branding', () => {
    const result: AnalysisResult = {
      inferencePoints: [],
      issues: [],
      summary: {
        totalInferencePoints: 0,
        criticalIssues: 0,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    const comment = generatePRComment(result);

    expect(comment).toContain('PeakInfer');
    expect(comment).toContain('peakinfer.dev');
  });
});

describe('Compact Comment', () => {
  test('Shows success for no critical issues', () => {
    const result: AnalysisResult = {
      inferencePoints: [{ id: 'ip-1', file: 'test.ts', line: 1, provider: 'openai', model: 'gpt-4' }],
      issues: [],
      summary: {
        totalInferencePoints: 1,
        criticalIssues: 0,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    const comment = generateCompactComment(result);

    expect(comment).toContain(':white_check_mark:');
    expect(comment).toContain('no critical issues');
  });

  test('Shows warning for critical/high issues', () => {
    const result: AnalysisResult = {
      inferencePoints: [],
      issues: [
        { id: 'i-1', severity: 'critical', category: 'cost', title: 'Test', description: 'Test', file: 'test.ts', line: 1 },
      ],
      summary: {
        totalInferencePoints: 1,
        criticalIssues: 1,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    const comment = generateCompactComment(result);

    expect(comment).toContain(':warning:');
    expect(comment).toContain('1 critical/high issues');
  });
});

describe('PR Blocking Logic', () => {
  test('Blocks on critical when threshold is critical', () => {
    const result: AnalysisResult = {
      inferencePoints: [],
      issues: [],
      summary: {
        totalInferencePoints: 0,
        criticalIssues: 1,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    expect(shouldBlockPR(result, 'critical')).toBe(true);
  });

  test('Does not block on high when threshold is critical', () => {
    const result: AnalysisResult = {
      inferencePoints: [],
      issues: [],
      summary: {
        totalInferencePoints: 0,
        criticalIssues: 0,
        highIssues: 5,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    expect(shouldBlockPR(result, 'critical')).toBe(false);
  });

  test('Blocks on high when threshold is high', () => {
    const result: AnalysisResult = {
      inferencePoints: [],
      issues: [],
      summary: {
        totalInferencePoints: 0,
        criticalIssues: 0,
        highIssues: 1,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    expect(shouldBlockPR(result, 'high')).toBe(true);
  });

  test('Does not block when no issues', () => {
    const result: AnalysisResult = {
      inferencePoints: [],
      issues: [],
      summary: {
        totalInferencePoints: 5,
        criticalIssues: 0,
        highIssues: 0,
        mediumIssues: 0,
        lowIssues: 0,
      },
    };

    expect(shouldBlockPR(result, 'critical')).toBe(false);
    expect(shouldBlockPR(result, 'high')).toBe(false);
    expect(shouldBlockPR(result, 'medium')).toBe(false);
  });
});
