/**
 * PR Comment generation for GitHub Actions
 */

import type { Insight, InferenceMap } from '../types.js';

export interface PRCommentInput {
  results: {
    inferenceMap: InferenceMap;
  };
  baseline: unknown | null;
  status: 'pass' | 'warning' | 'fail';
  regressions: unknown[];
  newIssues: Insight[];
  changedFiles: string[];
}

/**
 * Generate a PR comment from analysis results
 */
export function generatePRComment(input: PRCommentInput): string {
  const { results, status, newIssues } = input;
  const totalCallsites = results.inferenceMap.summary.totalCallsites;
  const lines: string[] = [];

  // Count issues by severity
  const critical = newIssues.filter(i => i.severity === 'critical');
  const warnings = newIssues.filter(i => i.severity === 'warning');
  const info = newIssues.filter(i => i.severity === 'info');

  // Determine verdict
  let verdict: { emoji: string; label: string; message: string };
  if (status === 'pass' || newIssues.length === 0) {
    verdict = {
      emoji: '✅',
      label: 'Safe to Merge',
      message: 'No issues found',
    };
  } else if (critical.length >= 2 || status === 'fail') {
    verdict = {
      emoji: '🔴',
      label: 'Changes Requested',
      message: `${critical.length} issues need attention before merge`,
    };
  } else if (critical.length === 1) {
    verdict = {
      emoji: '🟡',
      label: 'Review Recommended',
      message: '1 issue needs attention',
    };
  } else if (warnings.length > 5) {
    verdict = {
      emoji: '🟡',
      label: 'Review Recommended',
      message: `${newIssues.length} improvements suggested`,
    };
  } else if (warnings.length >= 1 && warnings.length <= 5) {
    verdict = {
      emoji: '🟢',
      label: 'Mostly Good',
      message: `${warnings.length} optional improvements`,
    };
  } else {
    verdict = {
      emoji: '✅',
      label: 'Safe to Merge',
      message: 'No issues found',
    };
  }

  // Verdict line
  lines.push(`**${verdict.emoji} ${verdict.label}** — ${verdict.message}`);
  lines.push('');

  // Summary
  lines.push(`Found ${totalCallsites} inference points`);
  lines.push('');

  // Top issue (if any)
  if (newIssues.length > 0) {
    // Sort by severity: critical > warning > info
    const sorted = [...newIssues].sort((a, b) => {
      const order = { critical: 0, warning: 1, info: 2 };
      return (order[a.severity] ?? 3) - (order[b.severity] ?? 3);
    });
    const topIssue = sorted[0];

    lines.push('**Top Issue**');
    lines.push(`**${topIssue.headline}**`);
    if (topIssue.location) {
      lines.push(`**Location:** \`${topIssue.location}\``);
    }
    if (topIssue.evidence) {
      lines.push(`**Why it matters**`);
      lines.push(topIssue.evidence);
    }
    lines.push('');

    // Collapsible details for multiple issues
    if (newIssues.length > 1) {
      lines.push('<details>');
      lines.push(`<summary>See all ${newIssues.length} issues</summary>`);
      lines.push('');

      // Group by severity
      if (critical.length > 1) {
        lines.push('**Critical**');
        for (const issue of critical.slice(1, 6)) {
          lines.push(`- ${issue.headline}${issue.location ? ` (\`${issue.location}\`)` : ''}`);
        }
        if (critical.length > 6) {
          lines.push(`- ... and ${critical.length - 6} more`);
        }
        lines.push('');
      }

      if (warnings.length > 0) {
        lines.push('**Warning**');
        for (const issue of warnings.slice(0, 5)) {
          lines.push(`- ${issue.headline}${issue.location ? ` (\`${issue.location}\`)` : ''}`);
        }
        if (warnings.length > 5) {
          lines.push(`- ... and ${warnings.length - 5} more`);
        }
        lines.push('');
      }

      if (info.length > 0) {
        lines.push('**Info**');
        for (const issue of info.slice(0, 5)) {
          lines.push(`- ${issue.headline}${issue.location ? ` (\`${issue.location}\`)` : ''}`);
        }
        if (info.length > 5) {
          lines.push(`- ... and ${info.length - 5} more`);
        }
        lines.push('');
      }

      lines.push('</details>');
      lines.push('');
    }
  }

  // Commands footer (only if issues exist)
  if (newIssues.length > 0) {
    lines.push('---');
    lines.push('**Commands:**');
    lines.push('- `/fix 1` - Apply fix for issue #1');
    lines.push('- `/dismiss 1` - Dismiss issue #1');
    lines.push('- `/fix all` - Apply all fixes');
    lines.push('- `/peakinfer` - Re-run analysis');
    lines.push('');
  }

  // Attribution
  lines.push('---');
  lines.push('*Generated by [PeakInfer](https://peakinfer.dev)*');

  return lines.join('\n');
}

/**
 * Generate a comment for exhausted credits
 */
export function generateExhaustedComment(used: number, limit: number): string {
  const lines: string[] = [];

  lines.push('## Free Tier Limit Reached');
  lines.push('');
  lines.push(`You've used ${used}/${limit} free credits.`);
  lines.push('');
  lines.push('**Options:**');
  lines.push('');
  lines.push('1. **Use BYOK mode** - Bring your own Anthropic API key');
  lines.push('2. **Upgrade to paid plan** - Get more credits');
  lines.push('3. **Run locally** - Install PeakInfer CLI:');
  lines.push('   ```bash');
  lines.push('   npm i -g @kalmantic/peakinfer');
  lines.push('   ```');
  lines.push('');
  lines.push('*Learn more at [peakinfer.dev](https://peakinfer.dev)*');

  return lines.join('\n');
}

