/**
 * PDF Generation Module
 * Converts HTML reports to well-formatted PDFs using Puppeteer
 *
 * Julie Zhou Design Principles:
 * - "Reports exist to enable sharing, not exploration"
 * - PDFs should be print-ready and professional
 */

import puppeteer from 'puppeteer';

// =============================================================================
// TYPES
// =============================================================================

export interface PDFOptions {
  format?: 'A4' | 'Letter';
  margin?: {
    top?: string;
    right?: string;
    bottom?: string;
    left?: string;
  };
  printBackground?: boolean;
}

// =============================================================================
// PUBLIC API
// =============================================================================

/**
 * Generate a PDF from HTML content
 * @param htmlContent - The HTML string to convert
 * @param outputPath - Where to save the PDF
 * @param options - PDF formatting options
 */
export async function generatePDF(
  htmlContent: string,
  outputPath: string,
  options: PDFOptions = {}
): Promise<void> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();

    // Set content and wait for styles to load
    await page.setContent(htmlContent, {
      waitUntil: 'networkidle0',
    });

    // Expand all <details> elements - PDFs are static, so collapsible sections must be open
    // Julie Zhou: "Reports exist to enable sharing, not exploration"
    await page.evaluate(`
      document.querySelectorAll('details').forEach(d => d.setAttribute('open', ''));
    `);

    // Add print-specific styles for better PDF rendering
    await page.addStyleTag({
      content: `
        @media print {
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .finding {
            break-inside: avoid;
          }
          details {
            break-inside: avoid;
          }
          section {
            break-inside: avoid-page;
          }
        }
      `,
    });

    // Generate PDF with professional formatting
    await page.pdf({
      path: outputPath,
      format: options.format || 'A4',
      margin: options.margin || {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm',
      },
      printBackground: options.printBackground !== false,
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 9px; color: #6b7280; width: 100%; text-align: center; padding: 5px 0;">
          PeakInfer Report
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 9px; color: #6b7280; width: 100%; display: flex; justify-content: space-between; padding: 5px 15mm;">
          <span>Generated by PeakInfer</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
    });
  } finally {
    await browser.close();
  }
}

/**
 * Convert HTML file to PDF
 * @param htmlPath - Path to the HTML file
 * @param pdfPath - Where to save the PDF
 */
export async function htmlFileToPDF(
  htmlPath: string,
  pdfPath: string
): Promise<void> {
  const { readFileSync } = await import('fs');
  const htmlContent = readFileSync(htmlPath, 'utf-8');
  await generatePDF(htmlContent, pdfPath);
}
